"use client"
import SideBar from '@/components/SideBar';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ProSidebarProvider } from "react-pro-sidebar";
import Navbar from './Navbar';




const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* wrapp everything with my side bar */}
        <ProSidebarProvider>
          <div className="flex">
            <div className='flex'>
              <SideBar/>
            </div>
            <div className='flex-1'>
              <Navbar/>
            {children}
            </div>
          </div>
          
        
        </ProSidebarProvider>
  
    </body>
    </html>
  )
}
